#!/bin/bash

DIR=.
cd $DIR
echo -e "\n$>>> $DIR\n"
git fetch origin master
OUTPUT=$(git diff origin/master)

if [[ -z $OUTPUT ]]; then
    echo "Local state matches origin/master"
    exit
fi

# reaches here only when any new content is present

git add --all

if [ "$1" == "" ]; then
    git commit -m 'semiautomated-update'
else
    git commit -m "$1"
fi

git merge -m "semiautomated-merge" origin/master
git push origin master


